Lmod Warning:
-------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: OpenSSL/1.1
(required by: nodejs/16.15.1-GCCcore-11.3.0)
-------------------------------------------------------------------------------



To connect to the notebook type the following command into your local terminal:
ssh -N -J tpelletreaudur@int5-pub.snellius.surf.nl tpelletreaudur@tcn587.local.snellius.surf.nl -L 5982:localhost:5982

After connection is established in your local browser go to the address:
http://localhost:5982
[I 12:41:59.066 NotebookApp] Serving notebooks from local directory: /gpfs/home3/tpelletreaudur/Probing-GNN-representations
[I 12:41:59.069 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 12:41:59.069 NotebookApp] http://localhost:5982/?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91
[I 12:41:59.069 NotebookApp]  or http://127.0.0.1:5982/?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91
[I 12:41:59.069 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:41:59.076 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///gpfs/home3/tpelletreaudur/.local/share/jupyter/runtime/nbserver-2978992-open.html
    Or copy and paste one of these URLs:
        http://localhost:5982/?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91
     or http://127.0.0.1:5982/?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91
[I 12:42:39.859 NotebookApp] 302 GET /?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91 (::1) 0.480000ms
/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 12:42:43.076 NotebookApp] 302 GET /?token=d181c9ab4e66cba6ecbfb43f6cfe8bd314fc3dbe84e72f91 (::1) 0.440000ms
[W 12:42:53.791 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-7' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-1' coro=<MultiKernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py:212>> is being executed.
[I 12:42:56.554 NotebookApp] Kernel started: b285450d-ee37-4d24-9b7c-107e681bc708, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 9249da11-0e03-42da-b433-4e8739535d82
[W 12:42:58.897 NotebookApp] 404 GET /static/components/codemirror/mode/plaintext/plaintext.js?v=20240926124157 (::1) 10.050000ms referer=http://localhost:5982/notebooks/Probing_GIN4.ipynb
[W 12:44:41.679 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-1' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-170' coro=<MultiKernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py:212>> is being executed.
[I 12:44:44.753 NotebookApp] Kernel started: 7993a697-e267-4e52-99e1-e7c40651ef1f, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 8ffb4710-7b0e-4687-9130-35b3cf20aebd
[W 12:44:46.255 NotebookApp] 404 GET /static/components/codemirror/mode/plaintext/plaintext.js?v=20240926124157 (::1) 5.980000ms referer=http://localhost:5982/notebooks/Probing_GIN4_dropout.ipynb
[I 12:44:58.746 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:44:58.747 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[W 12:44:58.941 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-9' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-259' coro=<MultiKernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py:212>> is being executed.
[I 12:45:01.566 NotebookApp] Kernel started: 0959804c-c13e-4dfe-9352-e9c6aa4ed90d, name: python3
[W 12:45:02.992 NotebookApp] 404 GET /static/components/codemirror/mode/plaintext/plaintext.js?v=20240926124157 (::1) 1.670000ms referer=http://localhost:5982/notebooks/Probing_GIN4_L2.ipynb
[I 12:46:58.656 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:46:58.657 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:47:02.899 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 12:47:02.900 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 12:47:33.595 NotebookApp] Saving file at /Probing_GIN4_dropout.ipynb
[W 12:47:33.596 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
[I 12:48:56.921 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:48:56.922 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:49:02.826 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 12:49:02.827 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 12:50:56.919 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:50:56.920 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:51:02.816 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 12:51:02.817 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 12:52:37.829 NotebookApp] Saving file at /Probing_GIN4_dropout.ipynb
[W 12:52:37.830 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
[I 12:52:56.930 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:52:56.931 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:53:02.781 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 12:53:02.782 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 12:54:57.029 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:54:57.030 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:57:42.949 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:57:42.950 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:57:43.420 NotebookApp] Saving file at /Probing_GIN4_dropout.ipynb
[W 12:57:43.421 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
[I 12:58:22.708 NotebookApp] Kernel interrupted: 7993a697-e267-4e52-99e1-e7c40651ef1f
[I 12:58:45.958 NotebookApp] Saving file at /Probing_GIN4_dropout.ipynb
[W 12:58:45.960 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
[I 12:58:56.959 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 12:58:56.960 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 12:59:03.307 NotebookApp] Kernel interrupted: b285450d-ee37-4d24-9b7c-107e681bc708
[I 13:00:45.898 NotebookApp] Saving file at /Probing_GIN4_dropout.ipynb
[W 13:00:45.899 NotebookApp] Notebook Probing_GIN4_dropout.ipynb is not trusted
[I 13:00:58.231 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:00:58.232 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:01:04.980 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:01:04.981 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:03:32.148 NotebookApp] Saving file at /models/models_BA_2grid_house.py
[I 13:03:35.942 NotebookApp] Starting buffering for 0959804c-c13e-4dfe-9352-e9c6aa4ed90d:537afbed7cac4f1ba23d6b9bd3bc8c58
[I 13:03:42.886 NotebookApp] Kernel restarted: 0959804c-c13e-4dfe-9352-e9c6aa4ed90d
[I 13:03:42.903 NotebookApp] Restoring connection for 0959804c-c13e-4dfe-9352-e9c6aa4ed90d:537afbed7cac4f1ba23d6b9bd3bc8c58
[I 13:03:42.903 NotebookApp] Replaying 1 buffered messages
[I 13:05:02.013 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:05:02.014 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:06:22.821 NotebookApp] Saving file at /models/models_BA_2grid_house.py
[I 13:06:34.296 NotebookApp] Starting buffering for b285450d-ee37-4d24-9b7c-107e681bc708:8b11c1b6f07a49b6925f4c533ebd74dd
[I 13:06:35.533 NotebookApp] Kernel restarted: b285450d-ee37-4d24-9b7c-107e681bc708
[I 13:06:35.548 NotebookApp] Restoring connection for b285450d-ee37-4d24-9b7c-107e681bc708:8b11c1b6f07a49b6925f4c533ebd74dd
[I 13:06:37.056 NotebookApp] Replaying 3 buffered messages
[I 13:06:56.934 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:06:56.935 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:07:42.880 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:07:42.881 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:08:57.891 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:08:57.892 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:09:42.898 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:09:42.899 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:10:57.036 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:10:57.037 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:12:56.966 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:12:56.967 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:15:02.942 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:15:02.943 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:15:42.966 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 13:15:42.967 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 13:15:45.284 NotebookApp] Kernel interrupted: 0959804c-c13e-4dfe-9352-e9c6aa4ed90d
[I 13:19:12.305 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:19:12.306 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 13:24:43.005 NotebookApp] Saving file at /Probing_GIN4_L2.ipynb
[W 13:24:43.006 NotebookApp] Notebook Probing_GIN4_L2.ipynb is not trusted
[I 14:00:57.954 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 14:00:57.957 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 14:04:57.228 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 14:04:57.229 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
[I 14:07:44.202 NotebookApp] Saving file at /Probing_GIN4.ipynb
[W 14:07:44.204 NotebookApp] Notebook Probing_GIN4.ipynb is not trusted
