To connect to the notebook type the following command into your local terminal:
ssh -N -J tpelletreaudur@int6-pub.snellius.surf.nl tpelletreaudur@gcn17.local.snellius.surf.nl -L 5339:localhost:5339

After connection is established in your local browser go to the address:
http://localhost:5339
[I 11:24:54.108 NotebookApp] Serving notebooks from local directory: /gpfs/home3/tpelletreaudur/Probing-GNN-representations
[I 11:24:54.108 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 11:24:54.108 NotebookApp] http://localhost:5339/?token=891453c8eb1a72de28d9c8994afedc80509af5b236c04c4f
[I 11:24:54.108 NotebookApp]  or http://127.0.0.1:5339/?token=891453c8eb1a72de28d9c8994afedc80509af5b236c04c4f
[I 11:24:54.108 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:24:57.318 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///gpfs/home3/tpelletreaudur/.local/share/jupyter/runtime/nbserver-2991589-open.html
    Or copy and paste one of these URLs:
        http://localhost:5339/?token=891453c8eb1a72de28d9c8994afedc80509af5b236c04c4f
     or http://127.0.0.1:5339/?token=891453c8eb1a72de28d9c8994afedc80509af5b236c04c4f
[I 11:29:08.624 NotebookApp] 302 GET /?token=891453c8eb1a72de28d9c8994afedc80509af5b236c04c4f (::1) 0.440000ms
/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-65' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
[I 11:38:21.206 NotebookApp] Kernel started: fb8a71c6-9535-429f-b116-d4793cfa0c51, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: aaae1363-bfd4-4a15-8102-a52a400b80b7
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-64' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-49' coro=<MultiKernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py:212>> is being executed.
[I 11:38:29.208 NotebookApp] Kernel started: 736cf5fb-b336-4d40-8c98-2e52b420c899, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 55d1338c-7522-4d49-8d74-b9dad6e98f1e
[I 11:40:20.734 NotebookApp] Saving file at /FC_probing_GIN.ipynb
[I 11:42:20.755 NotebookApp] Saving file at /FC_probing_GIN.ipynb
slurmstepd: error: *** JOB 7284891 ON gcn17 CANCELLED AT 2024-08-02T11:45:34 ***
[I 11:45:34.215 NotebookApp] Starting buffering for 736cf5fb-b336-4d40-8c98-2e52b420c899:1a35d51be76942018968015c70ce2007
[I 11:45:34.215 NotebookApp] Starting buffering for fb8a71c6-9535-429f-b116-d4793cfa0c51:24ef90f9305d4cc4b676414f54b7fae9

JOB STATISTICS
==============
Job ID: 7284891
Cluster: snellius
User/Group: tpelletreaudur/tpelletreaudur
State: CANCELLED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:03
CPU Efficiency: 0.01% of 06:16:12 core-walltime
Job Wall-clock time: 00:20:54
Memory Utilized: 2.33 GB
Memory Efficiency: 1.94% of 120.00 GB
